Apply application
hackwestern/hackwestern pull request #153
Opened 2024-09-25 22:28 UTC by elyknehc

closes/addresses (Github Issue number)

# Quick Overview of Changes

- (added x component)
- (added y function to a service on our backend)
Addresses ticket #118 
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/580aad34-8d61-462a-b295-b4f37627bd96">

# Checklist

- [ ] If any frontend changes were made, include a screenshot/demo in the overview
- [ ] Checked all uses of changed component(s)/function(s)
- [ ] If any changes were made to our backend services, at least one (happy path) unit test was added OR a `TODO` comment was added to create one.
- [ ] Check that CI is passing.
- [ ] If no (re-)reviews after 1-2 days, ping the web leads on the discord to remind them to review the PR.

**Note:** Weird thing that happens is that you can't see the footer on the page (need to scroll down) - someone pls help me with this 
@basokant @ArsalaanAli

2024-09-26 04:21 UTC, basokant requested changes

2024-09-26 04:21 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +    resolver: zodResolver(basicsSaveSchema),
u can change applicationSubmitSchema to basicSaveSchema here

2024-09-26 04:21 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +  function onSubmit(data: z.infer<typeof applicationSubmitSchema>) {
u can change applicationSubmitSchema to basicSaveSchema here

2024-09-26 04:21 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +                  {maxChars - charCount1} characters remaining
```suggestion
                  {maxChars - field.value.length} characters remaining
```

2024-09-26 04:21 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +                  {maxChars - charCount1} characters remaining
and same thing in the other places

2024-09-26 04:21 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +  const [charCount3, setCharCount3] = useState(0);
we can remove these with the change i suggested below

2024-09-26 04:21 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +import { applications } from "~/server/db/schema";
why do we need this?

2024-09-26 04:24 UTC, basokant requested changes

2024-09-26 04:24 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +  useAutoSave(form, onSubmit);
```suggestion
  useAutoSave(form, onSubmit, defaultValues);
```
so that the form initializes with the correct values

2024-09-26 19:06 UTC, basokant requested changes

2024-09-26 19:06 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +                  {maxChars - (field.value?.length ?? 0)} characters remaining
OH I just realized, this shouldn't be characters. Check the design

<img width="623" alt="image" src="https://github.com/user-attachments/assets/09e3d1df-ba24-4442-be38-90af19c29dd2">

2024-09-26 19:06 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +            Tell us why you think you will win Hack Western 11.
Here are the actual application questions

If you could have any superpower to help you during Hack Western, what would it be and why?
If you could build your own dream destination what would it look like? Be as detailed and creative as you want!
What project (anything you have ever worked on not just restricted to tech) of yours are you the most proud of and why? What did you learn throughout the process?

2024-09-26 19:12 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +                  {maxChars - (field.value?.length ?? 0)} characters remaining
With the current behaviour, negative remaining characters is possible which is a bit weird lol

2024-09-26 19:19 UTC, hunterchen7 commented on src/components/apply/form/application-form.tsx
> +  const maxChars = 150;
should be 150 words not 150 chars

2024-09-30 23:46 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +                    }}
basically what I'm saying is remove this for all 3

2024-09-30 23:49 UTC, basokant commented on src/components/apply/form/application-form.tsx
> +                  words remaining
change this to be "50/150 words"

2024-10-01 00:39 UTC, basokant approved these changes

2024-10-01 00:49 UTC, basokant approved these changes

2024-10-01 00:51 UTC, basokant approved these changes

2024-10-01 00:55 UTC, merged