#53 Create Application Review Queue endpoint
hackwestern/hackwestern pull request #92
Opened 2024-08-07 01:40 UTC by LordExodius

closes #53 

# Quick Overview of Changes

- Added `reviewRequestRouter`
- Created SQL queries to fetch applications for review

# Checklist

- [ ] If any frontend changes were made, include a screenshot/demo in the overview
- [ ] Checked all uses of changed component(s)/function(s)
- [ ] If any changes were made to our backend services, at least one (happy path) unit test was added OR a `TODO` comment was added to create one.
- [ ] Check that CI is passing.
- [ ] If no (re-)reviews after 1-2 days, ping the web leads on the discord to remind them to review the PR.

@basokant @ArsalaanAli

2024-08-07 03:47 UTC, hunterchen7 commented
don't merge, doesn't work 👎🏼

2024-08-23 00:28 UTC, basokant commented on src/server/api/root.ts
> -  review: reviewRouter,
don't replace the review router (I'm guessing this happened when resolving conflicts), either don't create a new router and add ur mutation to the existing reviewRouter (I'd recommend this), or create a new router here for ur reviewRequestRouter

2024-08-23 00:28 UTC, basokant requested changes
does not look good to me :((

2024-08-23 00:29 UTC, basokant commented on src/server/api/root.ts
> -  review: reviewRouter,
this is what's causing build errors lol

2024-08-23 01:35 UTC, basokant approved these changes
lgtm

2024-08-23 01:37 UTC, merged